codeready-toolchain/toolchain-common

.gitignore
README.adoc
README.md
deploy/idp.yaml
deploy/idp_secret.yaml
deploy/user.yaml

This is more for documentation purposes right now.

Manifests to configure IdP and create Users in OpenShift 4

---

README.adoc

chore: add badges on README

---

pkg/test/condition.go
pkg/test/condition_test.go

Extracted from https://github.com/codeready-toolchain/member-operator/pull/30

Add condition checkers (to be used by tests)

---

pkg/test/client.go

Extracted from https://github.com/codeready-toolchain/member-operator/pull/30

Introduce Fake Client (to be used in tests)

---

openshift-ci/Dockerfile.tools

install jq to parse CLONEREF_OPTIONS env var

---

deploy/idp.yaml
deploy/user.yaml

**Changes Proposed in this PR**
- update USERNAME as USER_NAME to not conflict with env USERNAME
- update idp configuration as per RHD

update IDP configuration parametes

---

pkg/test/client.go

add status update mock to fake client so I can mock calls that update the status

feat(test): add status update mock to fake client

---

README.adoc
pkg/test/masteruserrecord/doubles.go

Align types name for this https://github.com/codeready-toolchain/member-operator/pull/53/files#diff-c8f2c5e98ae9e5edbc54c3fdb15ead04R111-R117

align type name

---

pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

Overriding iat time for e2e tests to work

overriding iat time

---

pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

adding exp claim relating to this PR comment for e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/48#discussion_r347965838

adding exp extra claim

---

go.mod
go.sum
pkg/test/masteruserrecord/assertion.go

Required for https://github.com/codeready-toolchain/host-operator/pull/103

Switch to Cluster in UserAccount Embeded Status

---

pkg/template/processor_test.go
pkg/test/template.go

make functions helping with creation of template publicly available so it can be used in other repos

chore: make functions helping with creation of template publicly available

---

go.mod
go.sum
pkg/test/env.go
pkg/test/env_test.go

These functions were moved from registration-service repo + one additional function was added
see https://github.com/codeready-toolchain/registration-service/pull/80

feat: add functions for easy (un)setting variables in a test

---

go.mod
go.sum
pkg/cluster/kubefedcluster_test.go
pkg/test/masteruserrecord/doubles.go
pkg/test/useraccount/doubles.go

Updates to latest API and fixes tests which were broken by:
https://github.com/codeready-toolchain/api/pull/83
and
https://github.com/codeready-toolchain/api/pull/100

Update to latest API

---

pkg/test/useraccount/assertion.go

Adding assertion for userID and disabled fields based off of PR comment: https://github.com/codeready-toolchain/host-operator/pull/146/files#r379114633

Assertion for userid and disabled

---

go.mod
go.sum
pkg/test/masteruserrecord/doubles.go

Updating api version

---

go.mod
go.sum
pkg/cluster/kubefedcluster_assets.go
pkg/test/masteruserrecord/assertion.go

add assertions to check tier in MUR

feat: add assertions to check tier in MUR

---

pkg/client/client.go
pkg/client/client_test.go

fix test on updating resource

---

go.mod
go.sum
pkg/cluster/kubefedcluster_assets.go
pkg/test/client.go
pkg/test/condition.go
pkg/test/masteruserrecord/assertion.go
pkg/test/masteruserrecord/master_user_record.go
pkg/test/masteruserrecord/master_user_record_test.go
pkg/test/testing_t.go

include ClusterResources in MUR (in tests)

---

pkg/test/masteruserrecord/assertion.go
pkg/test/nstemplateset/assertion.go

also, rename `loadUaAssertion()` func to `loadMasterUserRecord()` in `pkg/test/masteruserrecord/assertion.go`

add NSTemplateSet fluent assertions

---

pkg/test/client.go

export Update and Create logic in FakeClient so it can be used externally while mocking the methods

chore: export Update and Create logic in FakeClient

---

pkg/test/useraccount/user_account.go

UserAccount modifier to specify deletionTimestamp

---

pkg/cluster/service.go

making it available for public use, in particular
in the e2e tests which need to setup a `ToolchainCluster`
resource to access the member cluster.
This is a follow-up PR of https://github.com/codeready-toolchain/toolchain-e2e/pull/152#discussion_r481819174

refactor cluster service method into public func

---

go.mod
go.sum
pkg/test/status.go

Add assertion for resource usage when comparing member statuses

feat: verify also resource usage when comparing member statuses

---

go.mod
go.sum
pkg/controller/toolchaincluster/healthchecker.go
pkg/controller/toolchaincluster/healthchecker_test.go

result of https://github.com/codeready-toolchain/api/pull/196
it just removes the code that retrieved the zones and the region

chore: drop zones & region from ToolchainCluster

---

scripts/add-cluster.sh

remove ClusterRole that is not needed anymore for ToolchainCluster CRs & logic

chore: remove ClusterRole from ToolchainCluster

---

scripts/add-cluster.sh

It adds support for sandbox config and download of "let's encrypt" certificate when requested

Support sandbox config

---

scripts/add-cluster.sh

the previous one retired - the new one should stay active for the next 5 years

fix: update certificate

---

pkg/condition/condition.go
pkg/condition/condition_blackbox_test.go

Required for https://github.com/codeready-toolchain/host-operator/pull/343

Add updateConditionsWithLastUpdatedTime()

---

pkg/test/status.go

refactor test: also check 'UserAccountCount' on member

---

scripts/add-cluster.sh

changes in OS 4.7:
* OLM creates two roles for the operator with the same prefix - we need to use the one with the label `olm.owner.kind=ClusterServiceVersion`
* let's use the same ToolchainCluster CR name format as in production, but we cannot use the EtcdDiscoveryName as it is not populated anymore: https://bugzilla.redhat.com/show_bug.cgi?id=1813012

chore: support changes in OS 4.7

---

pkg/condition/condition.go
pkg/condition/condition_blackbox_test.go

new func to verify if a condition exists

---

go.mod
go.sum
pkg/condition/condition.go
pkg/condition/condition_blackbox_test.go
scripts/add-cluster.sh

fix related to https://github.com/codeready-toolchain/host-operator/pull/403

added isFalse function

---

go.mod
go.sum
pkg/test/hostoperatorconfig.go

Adds functions for setting new field values in host operator config.
Signed-off-by: Shane Bryzak <sbryzak@gmail.com>

Added test functions for setting deactivating notification days

---

README.adoc

fix wrt: https://issues.redhat.com/browse/CRT-904

updated readme after removing minishift makefile targets in other repos

---

pkg/test/masteruserrecord/master_user_record.go

test: add MUR modifier to specify the spec.UserID

---

pkg/test/masteruserrecord/assertion.go
pkg/test/masteruserrecord/assertion_test.go
pkg/test/masteruserrecord/master_user_record.go
pkg/test/masteruserrecord/master_user_record_test.go
pkg/test/testing_t.go

test: add assertion on MUR annotations

---

make/lint.mk
pkg/condition/condition.go
pkg/status/toolchaincluster.go
pkg/test/client.go
pkg/test/masteruserrecord/assertion.go

refactor: GolangCI flags and fix lint issues

---

pkg/controller/toolchaincluster/toolchaincluster_controller.go
pkg/controller/toolchaincluster/toolchaincluster_controller_test.go

https://coreos.slack.com/archives/CHK0J6HT6/p1620732956300200

chore: rename controller types to Reconciler

---

go.mod
go.sum

update api to match with the latest version

chore: update api

---

pkg/controller/toolchaincluster/toolchaincluster_controller.go
pkg/controller/toolchaincluster/toolchaincluster_controller_test.go

see: https://github.com/codeready-toolchain/member-operator/pull/251

chore: adjust creation of controllers to latest operator-sdk format

---

go.mod
go.sum
pkg/test/doubles.go
pkg/test/masteruserrecord/master_user_record.go

include email address annotation on test MURs

---

pkg/states/state_manager.go
pkg/states/state_manager_test.go

This PR removes the Active() function from StateManager.

Removed unused Active() function

---

go.mod
go.sum

Updated to latest API

---

go.mod
go.sum
pkg/test/hostoperatorconfig.go
pkg/test/toolchainconfig.go
scripts/add-cluster.sh

Adds roles for the new `toolchainconfigs` and `memberoperatorconfigs` CRDs.
Related PR: https://github.com/codeready-toolchain/api/pull/236

Roles configs

---

go.mod
go.sum
pkg/test/config/toolchainconfig_assertion.go

Add common test assertions for toolchainconfig resources.

Add toolchainconfig assertions

---

go.mod
go.sum
pkg/test/config/toolchainconfig.go

See https://github.com/codeready-toolchain/host-operator/pull/463

add option to force metric synchronization from resources

---

go.mod
go.sum
pkg/test/config/memberoperatorconfig.go

Expands on the set of test functions to include the new memberoperatorconfig fields from https://github.com/codeready-toolchain/api/pull/246

Common test functions for dealing with memberoperatorconfig resources

---

scripts/add-cluster.sh

instead of reusing the ClusterRole created by OLM, let's just use the `cluster-admin` with full privileges.

feat: use cluster-admin ClusterRole for e2e ServiceAccounts

---

pkg/test/auth/tokenmanager.go

test: add 'Email' field to authsupport.Identity struct

---

pkg/configuration/test.go

Add MemberOperatorConfig test functions for creating and updating.

Add test functions for MemberOperatorConfig

---

pkg/client/client.go

export client from ApplyClient so it can be used outside of this repo

feat: export client from ApplyClient

---

go.mod
go.sum
pkg/test/useraccount/assertion.go

Required for https://issues.redhat.com/browse/CRT-1272

Add OriginalSub check to MatchMasterUserRecord assertions

---

go.mod
go.sum
pkg/test/condition.go
pkg/test/masteruserrecord/assertion.go
pkg/test/masteruserrecord/master_user_record.go
pkg/test/masteruserrecord/master_user_record_test.go
pkg/test/useraccount/assertion.go
pkg/test/useraccount/user_account.go
pkg/test/useraccount/user_account_test.go

more useraccount assertions

---

go.mod
go.sum
pkg/test/masteruserrecord/assertion.go
pkg/test/masteruserrecord/master_user_record.go

test: MasterUserRecord with default TierName

---

pkg/test/nstemplateset/nstemplateset.go
pkg/test/nstemplateset/nstemplateset_assertion.go

test: more funcs and assertions for NSTemplateSet resources 

---

go.mod
go.sum
pkg/test/config/toolchainconfig.go

Related issue: https://issues.redhat.com/browse/CRT-1319

Add config option for DefaultSpaceTier

---

pkg/test/condition.go
pkg/test/nstemplateset/nstemplateset.go
pkg/test/nstemplateset/nstemplateset_assertion.go

nstemplateset assertion: fix order of args

---

pkg/test/nstemplateset/nstemplateset.go

test: option to init an NSTemplateSet with a DeletionTimestamp

---

go.mod
go.sum
pkg/test/masteruserrecord/masteruserrecord.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go

Fixes https://issues.redhat.com/browse/CRT-1382

test: remove support for custom templates in NSTemplateSet

---

.github/workflows/ci-build.yml
.golangci.yml
controllers/toolchaincluster/healthchecker.go
controllers/toolchaincluster/toolchaincluster_controller.go
make/lint.mk
pkg/cluster/service.go
pkg/condition/condition_blackbox_test.go
pkg/template/processor.go
pkg/test/auth/tokenmanager_test.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go
pkg/test/tier/templateRefs.go

disable 'golint', use 'revive' instead

chore: update linter config

---

go.mod
go.sum
pkg/test/status.go

refactor: rename Member.APIEndpoint field

---

pkg/identity/identity_naming_standard.go
pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

Needed for tests for the following issue:
https://issues.redhat.com/browse/CRT-1398

Introduce username ExtraClaim to token manager

---

go.mod
go.sum
pkg/test/useraccount/useraccount.go
pkg/test/useraccount/useraccount_assertion.go

depends on https://github.com/codeready-toolchain/api/pull/293

feat: expect user email annotation to be set

---

go.sum

fix: run go mod tidy

---

go.mod
go.sum

refactor: rename 'ToolchainEvent' type to 'SocialEvent'

---

go.mod
go.sum
pkg/test/masteruserrecord/masteruserrecord.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go

related PRs https://github.com/codeready-toolchain/api/pull/297

refactoring: drop syncIndex

---

go.mod
go.sum
pkg/test/masteruserrecord/masteruserrecord_assertion.go
pkg/test/useraccount/useraccount_assertion.go

Related PRs:
- https://github.com/codeready-toolchain/host-operator/pull/625
- https://github.com/codeready-toolchain/api/pull/300

Update MatchMasterUserRecord assertion

---

.github/workflows/ci-build.yml

The go.mod replacements action in the host-operator and member-operator repos are nice. I think it would be useful in toolchain-common as well.

Add go.mod replacements action

---

pkg/notification/notification_builder.go
pkg/notification/notification_builder_test.go
pkg/test/usersignup/usersignup.go
pkg/usersignup/usersignup.go

Move notification Builder from host to toolchain-common
changes wrt - https://issues.redhat.com/browse/CRT-1418

move notification builder from host to common

---

go.mod
go.sum
pkg/test/nstemplateset/nstemplateset.go
pkg/test/nstemplateset/nstemplateset_assertion.go
pkg/test/nstemplateset/nstemplateset_assertion_test.go
pkg/test/nstemplateset/nstemplateset_test.go

test: SpaceRoles in NSTemplateSets

---

pkg/test/masteruserrecord/masteruserrecord_assertion_test.go

fix: comments in test

---

go.mod
go.sum
pkg/test/config/memberoperatorconfig.go

Related to https://github.com/codeready-toolchain/api/pull/314

Add SkipUserCreation option

---

go.mod
go.sum
pkg/test/socialevent/socialevent.go
pkg/test/usersignup/usersignup.go

see https://github.com/codeready-toolchain/registration-service/pull/267

test: SocialEvent helper func

---

go.mod
go.sum
pkg/test/nstemplateset/nstemplateset_test.go

Related PR: https://github.com/codeready-toolchain/api/pull/318

Remove deactivation timeout days

---

pkg/apis/apis.go
pkg/cluster/service.go

The proxy cache PR is coming: https://github.com/codeready-toolchain/registration-service/pull/275
This is a prerequisite.

Schema for auth required by proxy cache

---

pkg/client/client.go
pkg/client/client_test.go

See: 
- https://github.com/codeready-toolchain/host-operator/pull/677
- https://github.com/codeready-toolchain/member-operator/pull/376
- https://github.com/codeready-toolchain/toolchain-e2e/pull/589
- https://github.com/codeready-toolchain/sandbox-sre/pull/674

refactor: no need to wrap scheme in ApplyClient

---

controllers/toolchaincluster/healthchecker_test.go
pkg/cluster/service.go
pkg/cluster/service_whitebox_test.go
pkg/test/verify/cluster.go

changes related to https://github.com/codeready-toolchain/toolchain-cicd/pull/66
If the kubeconfig doesn't contain any certificate, then we need to support the insecure option. This is expected to be used only in dev/test environments because OSD clusters rely on Let's encrypt certificates anyway

feat: support insecure connection

---

go.mod
go.sum
pkg/test/config/toolchainconfig.go

In support of https://github.com/codeready-toolchain/registration-service/pull/278

Added functions to allow override of AWS configuration properties

---

pkg/test/socialevent/socialevent.go
pkg/test/socialevent/socialevent_test.go

changes to be used in https://github.com/codeready-toolchain/host-operator/pull/706

test: options for tiers in NewSocialEvent helper func

---

controllers/toolchaincluster/healthchecker.go
pkg/cluster/service.go

comment out unneeded logs

---

go.mod
go.sum
pkg/proxy/workspace.go
pkg/proxy/workspace_test.go

Helper functions for space lister and tests
Depends on https://github.com/codeready-toolchain/api/pull/337

Workspace helper

---

go.mod
go.sum
pkg/proxy/workspace.go

Helper functions to add workspace type to the Workspace.Status in the proxy space lister responses.

Add workspace type helper

---

pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

Required for https://issues.redhat.com/browse/CRT-1718

Added support for user_id and account_id extra claims in token manager

---

pkg/apis/apis.go

replaces https://github.com/codeready-toolchain/toolchain-common/pull/302
/assign @alexeykazakov

PLNSRVCE-1166: add openshift route type to scheme for registration service proxy plugin support 

---

.github/workflows/ci-build.yml
pkg/cluster/cache_whitebox_test.go
pkg/identity/identity_naming_standard.go
pkg/predicate/predicate.go
pkg/test/config/toolchainconfig.go
pkg/test/env.go
pkg/test/testing_t.go

chore: upgrade GolangCI Lint to v1.52.0

---

go.mod
pkg/client/rest_client.go
pkg/client/rest_client_test.go
pkg/test/rest_client.go

Add `CreateTokenRequest` and testing utilities.
Jira: https://issues.redhat.com/browse/ASC-258

feat: Implement "copy secret" functionality in SpaceRequest controller

---

pkg/client/client.go
pkg/client/client_test.go

Add patch support for SA objects.
Jira: https://issues.redhat.com/browse/SANDBOX-87
Related PR: https://github.com/codeready-toolchain/member-operator/pull/453

feat: add support for patching service account resources in member operator

---

pkg/client/client.go
pkg/client/client_test.go
pkg/hash/hash.go
pkg/hash/hash_test.go
pkg/test/nstemplateset/nstemplateset.go
pkg/test/nstemplateset/nstemplateset_test.go
pkg/test/space/space.go
pkg/test/space/space_assertions.go

and make it available for other repos including sandbox-sre

test(spaces): move from host-operator repo

---

pkg/spacebinding/spacebinding.go
pkg/spacebinding/spacebinding_test.go

Needed for https://issues.redhat.com/browse/SANDBOX-287

Add option to set role for new spacebinding

---

pkg/test/config/toolchainconfig.go

Add few utilities for unit testing sbr in host-operator.
Jira: https://issues.redhat.com/browse/ASC-414
Related PR: https://github.com/codeready-toolchain/host-operator/pull/857

feat: update SpaceBinding cleanup controller to delete SBR resources

---

pkg/test/masteruserrecord/masteruserrecord.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go
pkg/test/useraccount/useraccount.go

related PR https://github.com/codeready-toolchain/host-operator/pull/872

add a few helper functions for UserAccounts

---

controllers/toolchaincluster/healthchecker.go
controllers/toolchaincluster/healthchecker_test.go
controllers/toolchaincluster/toolchaincluster_controller.go

Signed-off-by: Francesco Ilario <filario@redhat.com>

fix: forward context in toolchaincluster controller

---

pkg/client/client.go
pkg/client/client_test.go

Required by [member-operator#502](https://github.com/codeready-toolchain/member-operator/pull/502) and [host-operator#929](https://github.com/codeready-toolchain/host-operator/pull/929)
Signed-off-by: Francesco Ilario <filario@redhat.com>

fix: forward context in common pkg/client

---

pkg/notification/notification_builder.go
pkg/notification/notification_builder_test.go
pkg/test/usersignup/usersignup.go

Related Issue: https://issues.redhat.com/browse/SANDBOX-483

Refactor to only use UserSignup identity claims

---

go.mod
go.sum
pkg/test/config/toolchainconfig.go

Requires https://github.com/codeready-toolchain/api/pull/392

SSO configuration for web login

---

.golangci.yml
pkg/client/client_test.go
pkg/cluster/service_test.go
pkg/configuration/cache_test.go
pkg/configuration/load_test.go
pkg/spacebinding/spacebindinglister_test.go
pkg/status/componentconditions_test.go
pkg/status/toolchaincluster_test.go
pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go
pkg/test/client_test.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go
pkg/test/nstemplateset/nstemplateset_assertion.go
pkg/test/socialevent/socialevent_test.go

also, disable rule on dot-imorts (ie, make always permitted)

chore: fix linter issues

---

go.mod
go.sum

Associated API PR: https://github.com/codeready-toolchain/api/pull/400

Update UserSignup.Spec.IdentityClaims to be required

---

controllers/label_event_handler_test.go

fix linter : https://github.com/codeready-toolchain/toolchain-common/actions/runs/8552225966/job/23432889172?pr=382

go fmt file

---

sonar-project.properties

attempt to fix sonar coverage not being reported

add sonar coverage config

---

go.mod
go.sum
pkg/configuration/get.go
pkg/configuration/get_test.go

Needed for https://issues.redhat.com/browse/SANDBOX-653

Add GetUint() to configuration utils

---

pkg/test/config/toolchainconfig.go

Needed for https://issues.redhat.com/browse/SANDBOX-653

Add feature toggles to config test util

---

pkg/test/nstemplateset/nstemplateset.go
pkg/test/nstemplateset/nstemplateset_assertion.go
pkg/test/space/space.go
pkg/test/space/space_assertions.go

Needed for https://github.com/codeready-toolchain/host-operator/pull/1048

Add annotation utils to space and nstemplateset test utils

---

go.mod
go.sum
pkg/test/config/toolchainconfig.go

This PR adds changes for Public-Viewer support.
[JIRA [ASC-532](https://issues.redhat.com//browse/ASC-532)](https://issues.redhat.com/browse/ASC-532)

add PublicViewerConfig in test pkg

---

controllers/toolchaincluster/toolchaincluster_controller_test.go
pkg/cluster/service.go
pkg/condition/condition_blackbox_test.go
pkg/template/nstemplatetiers/nstemplatetier_generator_test.go
pkg/test/assertions/assertions_test.go

- improve assertions
- remove imports being imported more than once
- fix typo

improve assertions and remove imports being imported more than once

---

go.mod
go.sum
pkg/configuration/memberoperatorconfig/configuration.go
pkg/configuration/memberoperatorconfig/configuration_test.go
pkg/test/config/memberoperatorconfig.go

https://issues.redhat.com/browse/SANDBOX-659

Add Autoscaler Buffer CPU to configuration

---

go.mod
go.sum
pkg/test/socialevent/socialevent.go
pkg/test/socialevent/socialevent_test.go

Part of https://issues.redhat.com/browse/SANDBOX-724

Add target cluster option to social event test util

---

pkg/test/metrics/metric.go

test: metric assertions and coomparisons

---

pkg/test/metrics/metric.go

new helper func to obtain a Prometheus counter value

test: metric helper func

---

.golangci.yml

remove unsupported service:
`$ golangci-lint config verify --config=./.golangci.yml jsonschema: "" does not validate with "/additionalProperties": additional properties 'service' not allowed `
Similar Prs
- Member-operator - https://github.com/codeready-toolchain/member-operator/pull/626
- Host Operator - https://github.com/codeready-toolchain/host-operator/pull/1143
- Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1120
- Toolchain - common - https://github.com/codeready-toolchain/toolchain-common/pull/458
- Api - https://github.com/codeready-toolchain/api/pull/461 
- Registration Service - https://github.com/codeready-toolchain/registration-service/pull/511

Updating .golangci.yml config removing unsupported service

---

.github/workflows/govulncheck.yml
go.mod
go.sum

improve govulncheck gh action

---

CODEOWNERS

JIRA: https://issues.redhat.com/browse/SANDBOX-1043

chore: Remove kanika from owners
