codeready-toolchain/toolchain-common

README.adoc
README.md
scripts/add-cluster.sh

add script `add-cluster.sh` that takes two arguments:
1. type of the cluster to be added
2. name of the cluster to be added
- The script is working with minishift profiles and expects that there are only two clusters (profiles) called `host` and `member`
- to be able to run the script, you need to have both clusters prepared, which means:
- created CRDs
- created SA with cluster role binding 
- what does the script do? When you want to add a Member cluster to the system, then you run `add-cluster.sh member member-cluster` and the script:
1. goes to the member profile
2. takes a secret of the SA (from the member)
3. takes API endpoint of the member cluster from Kube config
4. goes to host cluster
5. creates a secret with the SA token taken from the member
6. creates KubeFedCluster …

feat: add add-cluster.sh script

---

go.mod

otherwise, repositories that depend on it cannot be built

chore: rename module to toolchain-common

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go

the function is going to be used in a member operator to get a client of a host cluster - the member doesn't know the name of the cluster and there should be only one `KubeFedCluster` CR in the namespace

feat: add func returning first cluster client from cache

---

make/go.mk

`make build` doesn't give us much since there is no executables provided by this repo. But it might be useful to have some target which we could use for quick compilation error check rather than always relaying on the test execution (which can be longer).
@xcoulon thoughts?

Add make build

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go

We discussed with Shane some helper/utility functions which will get us access to the Host and Member clusters.
We can't relay on the first cluster or on all available clusters. Because it may happen that some physical cluster acts us a member and as a host. So, such cluster will have mixed types of clusters in the cache.
So, using the existing `GetFirstCluster()` is not safe.
@MatousJobanek @sbryzak, WDYT?
TODO:

Add helper functions to get host and member clusters

---

README.adoc
pkg/cluster/cache.go
pkg/cluster/service.go
pkg/cluster/service_test.go
scripts/add-cluster.sh

the label `localName` will help members to identify themselves in the host. 
The script takes a name of the cluster from the kube config - this is kind of temporary solution for minishift until we will be able to use `clusterID` in OS 4

feat: add localName label to KubeFedCluster CR

---

make/test.mk

use 'ifneq' condition to distinguish the case where the job
is building a PR or after the PR was merged on master, in which
case the commit is not the same (and there is no PR number)

upload report on PR merge

---

go.mod
go.sum
pkg/test/e2e/awaitility.go
pkg/test/e2e/doubles.go
pkg/test/e2e/kubefed.go

This PR adds:
* function for setting up e2e test that uses both operators (host and member)
* doubles that help with waiting for the availability of KubeFedCluster CRs
* skeleton for KubeFedCluster e2e test that will be used in both repositories host and member

feat(CRT-165,CRT-202): add skeleton for KubeFedCluster e2e test & add test doubles for running e2e test with both operators

---

pkg/test/e2e/awaitility.go
pkg/test/e2e/kubefed.go

add controller client to Awaitility to be able to run status requests, otherwise, it's not possible to trigger status sync from host

feat: add controller client to Awaitility to be able to run status requests

---

pkg/test/client.go
pkg/test/client_test.go

This PR introduces `Get()` and `List()` mock functions to the mock client.
Also it adds `ctx context.Context` param to all mock functions because sometimes it's needed in our tests. This change breaks API but it's pretty easy to fix the existing tests to support `ctx` param.

Add Get and List to fake client

---

pkg/controller/kubefedcluster_caching.go

watch KubeFedCluster only within operator namespace so it doesn't register instances in other namespaces. Mainly when there are a running member and host operators in the same cluster. 
modification of e2e tests in both clusters will follow

fix: watch KubeFedCluster only within operator namespace

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go

add funcs to match the existing func signatures
add vars to match the existing funcs
these new funcs and vars can be used in controllers

add var and func to get host and member clusters

---

pkg/cluster/cache_whitebox_test.go

Because the cluster cache is stored as a map we can't guarantee the order of stored clusters. And we have to take it into account when testing.

Fix flaky cluster cache test

---

.golangci.yml
make/lint.mk

add 'golangci.yml' file with a timeout to 10min
and the same linter config as in host-operator
for now
fixes CRT-297

configure golangci-lint

---

README.adoc
scripts/add-cluster.sh

In case we need to register two separated clusters as a member and a host, we need to specify the target URLs and login to them.
Introduced a new parameter `--minishift` - if the parameter is not set and the parameter `--single-cluster` neither, then the script asks for cluster URL and the token:
```
Write the server url for the cluster type: host:
> https://api.host.crt-stage.com:6443
Provide the token to log in to the cluster https://api.host.crt-stage.com:6443:
> 
Logged into "https://api.host.crt-stage.com:6443" as "mjobanek-crtadmin" using the token provided.
```
similarly for the member cluster

chore: support separated clusters when registering host and member

---

pkg/cluster/cache.go
pkg/cluster/service.go
pkg/cluster/service_test.go

Required for https://jira.coreos.com/browse/CRT-348
This APIEndpoint from KubeFedCluster will be used by MUR controller to properly setup user account status. See https://github.com/codeready-toolchain/api/pull/59

Add APIEndpoint to FedCluster

---

README.adoc
scripts/add-cluster.sh

Currently, we are working on infrastructure setup script, which will do the following
- Creates host and member cluster
- Setup IDP
- Create all admin users
- Deploy operators
- Setup KubeFed
For the last point, we need two different cluster credentials kubeconfig to be provided to switch the context and login to respective cluster using context.
This script assumes that if user is passing kubeconfig then it needs to have context with `host-admin` and `member-admin`

add kubeconfig option to avoid prompt

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go
pkg/cluster/kubefedcluster_assets.go
pkg/cluster/service.go
pkg/cluster/service_test.go
pkg/cluster/service_whitebox_test.go
pkg/controller/kubefedcluster_caching.go
pkg/test/client.go
pkg/test/cluster.go

Refresh KubeFedCluster cache when a cluster is not found to avoid a situation that the cache could miss any cluster added before or during the deployment startup

fix: refresh cluster cach when a cluster is not found

---

pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

in order to update registration-service to use the latest common we need to provide a way to override the sub and nbf claims. 
relates to: https://github.com/codeready-toolchain/registration-service/pull/79

overriding sub and nbf claims

---

go.mod
go.sum
pkg/client/client_test.go
pkg/test/client.go
pkg/test/client_test.go

Some existing tests relay on resource Generation changes which is currently are ignored by the fake client.
This PR https://github.com/codeready-toolchain/toolchain-common/pull/88/files#diff-fb87476fa66849c8514ba700e715b4b6R108
fixed a bug in `ApplyClient` which actually broke some of our tests (sounds weird I know).
Let's add generation updates in our fake client so it's available in all our tests.

Update Generation in Fake client

---

pkg/test/masteruserrecord/master_user_record_test.go
pkg/test/testing_t.go

this allows for casting the current `testing.T`
with `assert.T` in https://github.com/stretchr/testify/assert
Updates https://issues.redhat.com/browse/CRT-459

add methods to test.T interface

---

pkg/cluster/kubefedcluster_assets.go
pkg/template/processor.go
pkg/template/processor_test.go

This will be useful to determine if objects were created or updated by our operators.

refactor: return create/update status when applying tmpl objects

---

pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

adding extra claims that will be used when writing e2e-tests for the additional fields that the notification service messages require.
jira: https://issues.redhat.com/browse/CRT-518

adding extra claims for notification service messages

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go

When no FedCluster of the given type is found, then refresh the cache. This is for the cases 
* when there is a rolling update 
* when a pod panicked and a new one started 
so the member operator can immediately start operating with the already existing resources. 
Otherwise, the provisioning/update may fail with an error: `unable to connect to the host cluster: unknown cluster`
paired PRs:
https://github.com/codeready-toolchain/host-operator/pull/185
https://github.com/codeready-toolchain/member-operator/pull/145

feat: when no FedCluster is found then refresh the cache

---

pkg/client/client.go
pkg/client/client_test.go
pkg/cluster/cache_whitebox_test.go
pkg/cluster/kubefedcluster_assets.go
pkg/template/processor.go
pkg/template/processor_test.go
pkg/test/template.go

proposed changes:
* moved apply method from processor to client - it makes more sense to have it there
* also moved the related tests
* added "labels" parameter to the apply method so we can let the client take care of it and we can make the NSTemplateSet controller a bit simpler :-) 
* decreased a bit the concurrent test of fedcluster cache - it was too much and my PC had problems with the number of concurrent goroutines

feat: move apply to client and assign labels when applying

---

pkg/test/client.go
pkg/test/client_test.go

If the resource is not updated, then we should just pass the generation value.
related member-operator PR: https://github.com/codeready-toolchain/member-operator/pull/149
there is no need to change in host-operator repo

fix: only pass generation when resource wasn't updated

---

go.mod
go.sum
pkg/condition/condition.go

Related PR: codeready-toolchain/api#158
This PR adds `LastUpdatedTime` to the condition each time the common function `addOrUpdateStatusCondition` is called. This is required because the API returns an error if it's not included:
```
{"level":"error","ts":1592429640.32348,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"registrationservice-controller","request":"rsenthil-host-operator/registration-service","error":"RegistrationService.toolchain.dev.openshift.com \"registration-service\" is invalid: status.conditions.lastUpdatedTime: Invalid value: \"null\": status.conditions.lastUpdatedTime in body must be of type string: \"null\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/rajiv/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ns …
```

Add LastTransitionTime to conditions

---

go.mod
go.sum
pkg/condition/condition.go

Reverts https://github.com/codeready-toolchain/toolchain-common/pull/112 since it is not needed for resources other than MemberStatus and Toolchain Status.
https://github.com/codeready-toolchain/api/pull/160 makes the api optional so it does not need to be added to the status for other resources at all.

Revert last updated time

---

pkg/test/status.go

This PR adds some test assertions that will be used by toolchain status tests in the host-operator repo.
Related issue: https://issues.redhat.com/browse/CRT-731

Add toolchainstatus assertions

---

pkg/status/componentconditions.go
pkg/status/componentconditions_test.go
pkg/status/deployment.go
pkg/status/deployment_test.go
pkg/status/kubefed.go
pkg/status/kubefed_test.go
pkg/test/condition.go

Related issue: https://issues.redhat.com/browse/CRT-729
Use toolchainv1alpha1.Condition type for kubefed conditions so that all toolchain components can report their status using the same condition types for a uniform implementation.
Errors do not need to be returned with the conditions because they are already included in the conditions.
Related PRs:
https://github.com/codeready-toolchain/member-operator/pull/181
https://github.com/codeready-toolchain/host-operator/pull/254

Use toolchainv1alpha1.Condition type for toolchain component status

---

pkg/test/masteruserrecord/master_user_record.go

Adding a couple MurModifiers for automatic user deactivation unit tests:
- One for setting the ProvisionedTime on the MUR status
- One for taking a UserSignup and using its name as MUR UserID

Changes for testing auto user deactivation

---

pkg/predicate/predicate.go
pkg/predicate/predicate_test.go

Move predicate package from member repo to toolchain-common so that it can be used by the host operator controllers as well.

chore: Move predicate from member repo to toolchain-common

---

pkg/status/toolchaincluster.go
pkg/status/toolchaincluster_test.go

Instead of transforming a `Duration` into a string and then parsing the string back to `Time` let's use the functions provided by `time.*` package

chore: refactor check of the last probe

---

pkg/cluster/cache.go

extracts the cluster filter logic to an exported function so it can be used outside of this project/package

chore: extract cluster filter logic

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go
pkg/cluster/service.go
pkg/test/hostoperatorconfig.go

Drop the capacity exhausted flag from the `ToolchainCluster` - this is replaced by setting the capacity thresholds in `HostOperatorConfig`
It also extracts the cluster filter logic to an exported function so it can be used outside of this project/package

chore: drop capacity exhausted flag and extract cluster filter logic

---

scripts/add-cluster.sh

We need to delete the bindings since we cannot change the `roleRef` of the existing bindings - running the script twice fails with: 
```
for: "STDIN": RoleBinding.rbac.authorization.k8s.io "toolchaincluster-host-operator" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"toolchaincluster-host-operator"}: cannot change roleRef
```

fix: delete role binding before creating

---

scripts/add-cluster.sh

The add-cluster.sh script should fail when any of the commands fails
It picks the first found ClusterRole - it's useful for local testing when there are multiple deployments with multiple ClusterRoles present in the cluster.

fix(add-cluster.sh): fail when some subcommand fails  & pick first found ClusterRole

---

scripts/add-cluster.sh

the key `serverApi` was renamed to `serverAPI` in sanbox.yaml files - we need to reflect the change also here

fix: reflect changes in sandbox.yaml file

---

go.mod
pkg/client/client.go
pkg/client/client_test.go
pkg/test/masteruserrecord/assertion.go

This field is part of the spec but it is immutable, so we
have to retain the existing value when performing an update.
Otherwise, we get this kind of error:
```
Service "<name>" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
Since the object arg can be explicitely a `corev1.Service` or
an `unstructured.Untructured` (if coming from a template), we need
to support both cases.
Also: reorganized the tests (and added a few more!)

fix: retain Service's 'spec.ClusterIP' field during update

---

pkg/client/client.go
pkg/client/client_test.go

refactor: extract func to retain ClusterIP on a service object

---

pkg/client/client.go
pkg/client/client_test.go

move the `owner` and `forceUpdate` parameters as options,
add add an option to avoid saving the configuration
(which causes troubles when the resource is too big, for example,
a ConfigMap with large JSON files)

refactor: use options to create or update object

---

scripts/add-cluster.sh

We cannot create Role for non-existing resource kinds in member cluster in OSD. 
I'm referring to the new member cluster where we install only member operator and not the host one - that means that we don't have host CRDs available there

fix: split role for toolchain-cluster SAs

---

scripts/add-cluster.sh

since we need to add a second member cluster with a different API as well as name to the host, we need to know where the ToolchainCluster representing host should be created - to achieve that we should use the new `--target-cluster` parameter

feat: add possibility to specify target cluster

---

scripts/add-cluster.sh

use simple type name in owner ownerClusterName label, otherwise, it will contain a prefix equal to the name from the sandbox.yaml file: `member-2-us-east-2a-sandbox-m2.ll9k.p1.openshiftapps.com`

fix: use simple type name in owner ownerClusterName label

---

pkg/predicate/predicate.go
pkg/predicate/predicate_test.go

Related issue: https://issues.redhat.com/browse/CRT-941
Adds a new predicate to only reconcile update events if Generation or Labels have changed.

Add new labels and generation predicate

---

go.mod
go.sum
pkg/test/condition.go
pkg/test/status.go

Adding ApiEndpoint compare check in AssertContainsMember - for toolchain status unit tests.
fix related to: https://issues.redhat.com/browse/CRT-971
related PR: https://github.com/codeready-toolchain/host-operator/pull/394

Adding to check ApiEndpoint in MemberStatus for host-operator unit tests

---

scripts/add-cluster.sh

We need to delete ClusterRoleBinding before applying because we cannot update `roleRef` and this is needed when we need to rerun the setup in one cluster multiple times.
We didn't face it before because OLM created ClusterRoles with the fixed name

fix: delete ClusterRoleBinding before applying it

---

pkg/states/state_manager.go
pkg/states/state_manager_test.go

This PR set the UserSignup deactivating state to false when deactivated is set to true.
Part of https://issues.redhat.com/browse/CRT-1006

Set deactivating state to false when deactivated set to true

---

pkg/states/state_manager.go
pkg/states/state_manager_test.go

Simple PR, which sets the `deactivated` and `deactivating` states to false when a user is approved.
Fixes https://issues.redhat.com/browse/CRT-1015

Set UserSignup deactivated state to false when approved

---

.github/workflows/ci-build.yml

upgrade underlying GolangCI action to 1.39
Do not use cache and avoid tons of errors such as:
```
Error: /usr/bin/tar: ... : Cannot open: File exists
```
Fixes https://issues.redhat.com/browse/CRT-1108

lint: configure GitHub Action

---

go.mod
pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

The satori uuid library is no longer maintained and contains some serious flaws ([details](https://github.com/gofrs/uuid#project-history)), we shouldn't be using it any more.

Replace satori uuid lib with gofrs

---

.github/workflows/ci-build.yml

using an LTS version instead of `lastest`
Fixes https://issues.redhat.com/browse/CRT-1033

build: run GitHub Actions on Ubuntu 20.04

---

pkg/test/config/memberoperatorconfig.go

Adds a function `ModifyMemberOperatorConfig` that allows to reuse the `MemberOperatorConfigOption` functions for modifying a `MemberOperatorConfig` resource.

Add ModifyMemberOperatorConfig for tests

---

pkg/test/config/memberoperatorconfig.go

Webhook image is an env var bundled with the operator.

Remove webhook image because it will be an env var

---

pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go
pkg/cluster/service.go
pkg/status/toolchaincluster.go

while working on e2e tests I faced several times this kind of error in the member operator log:
```
2021-07-01T15:57:14.261Z        ERROR   controller-runtime.manager.controller.memberstatus      the last probe happened before: 9.261310055s, see: &{Conditions:[{Type:Ready Status:True LastProbeTime:2021-07-01 15:57:05 +0000 UTC LastTransitionTime:2021-07-01 15:51:53 +0000 UTC Reason:ClusterReady Message:/healthz responded with ok}]} {"reconciler group": "toolchain.dev.openshift.com", "reconciler kind": "MemberStatus", "name": "toolchain-member-status", "namespace": "toolchain-member-01154907", "error": "exceeded the maximum duration since the last probe: 8s"}
```
It also happened that my e2e tests failed a few times because of that.
I checked the logs in production and the same error …

fix: create client only when ToolchainCluster config changed

---

scripts/add-cluster.sh

it's verbose and probably useless if we need to debug the tests.

script: hide CABundle when printing the ToolchainCluster CR

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/toolchain_object.go
pkg/template/processor_test.go
pkg/test/client.go

Fixes https://issues.redhat.com/browse/CRT-1182
see also: https://github.com/codeready-toolchain/member-operator/pull/297, https://github.com/codeready-toolchain/toolchain-e2e/pull/384 and https://github.com/codeready-toolchain/registration-service/pull/215

refactor: use `client.Object` instead of `meta.Accessor()`

---

pkg/cluster/service.go

So the member cluster client (used by host) can get Secrets and Service Accounts. It's required for the proxy.

Add kube core api group to member client

---

controllers/toolchaincluster/healthchecker.go
pkg/cluster/cache.go
pkg/cluster/cache_whitebox_test.go
pkg/cluster/service.go
pkg/cluster/service_test.go
pkg/status/toolchaincluster_test.go
pkg/test/verify/cluster.go

This PR introduces a `Config` type in cluster package - it more or less represents the configuration of ToolchainCluster. There is nothing new in there - just moving the params around.
The reason for that is that in host-operator we need to list all cluster configs for member clusters to be able to add it to Manager.
related PRs:
https://github.com/codeready-toolchain/host-operator/pull/542
https://github.com/codeready-toolchain/member-operator/pull/312
https://github.com/codeready-toolchain/toolchain-e2e/pull/412
https://github.com/codeready-toolchain/registration-service/pull/229

feat: introduce cluster Config and a way to list them

---

pkg/cluster/service.go
pkg/cluster/service_whitebox_test.go

This is the real fix for the weird behavior that I saw in our logs. We should compare the `rest.Config` when checking if the new client should be created.
related PRs: 
https://github.com/codeready-toolchain/member-operator/pull/320
https://github.com/codeready-toolchain/host-operator/pull/561

fix: compare rest.Config and not cluster.Config

---

go.mod
pkg/test/masteruserrecord/masteruserrecord.go
pkg/test/masteruserrecord/masteruserrecord_test.go
pkg/test/useraccount/useraccount_test.go

renamed `TierName` UaInMurModifier to `UserAccountTierName`

test: modifier to set spec.tiername in MasterUserRecord

---

pkg/test/nstemplateset/nstemplateset.go

Adds a NSTemplateSet modifier to fill namespace and clusterresource refs for a given tier.
Related PR: https://github.com/codeready-toolchain/host-operator/pull/568

Add NSTemplateSet modifier to fill namespace and clusterresource refs

---

pkg/test/config/toolchainconfig_assertion.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go

- rename `Assertion` to `MasterUserRecordAssertion` for assertions on
a single MasterUserRecord
- rename `Assertion.masterUserRecord` to `MasterUserRecordAssertion.mur`
- introduce `MasterUserRecordsAssertion` for assertions on
multiple MasterUserRecords (counting, etc.)
- add multiple assertions methods to be used in `UserSignupController` tests.
changes to be used in https://github.com/codeready-toolchain/host-operator/pull/569

test: refactor MasterUserRecord assertion

---

pkg/test/useraccount/useraccount.go
pkg/test/useraccount/useraccount_assertion.go

- Updates the `NewUserAccountFromMur` func to set the tier label
- Adds `HasLabelWithValue` assertion on UserAccount
Related PR: https://github.com/codeready-toolchain/host-operator/pull/580

Set tier label on useraccount

---

pkg/cluster/service.go

revert unneeded changes after gosec linter complains
use `// nolint:gosec` comment instead.

chore: revert linter changes

---

pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

Removes the "username" utility function, we need to use "preferred_username" instead.

Should just use preferred_username claim, not username

---

pkg/test/masteruserrecord/masteruserrecord.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go
pkg/test/masteruserrecord/masteruserrecord_test.go
pkg/test/useraccount/useraccount.go
pkg/test/useraccount/useraccount_test.go

Related PR: https://github.com/codeready-toolchain/host-operator/pull/595
Relates Issues:
https://issues.redhat.com/browse/CRT-1320
https://issues.redhat.com/browse/CRT-1323
- Removes test functions related to NSLimit and NSTemplateSet in UserAccount
- Removes tier hash label from MasterUserRecord

Remove user account tier checks

---

pkg/identity/identity_naming_standard.go
pkg/identity/identity_naming_standard_test.go

This PR modifies the identity name compliance check to ensure the name is compliant with Openshift's naming standard, not the DNS-1123 standard as previous.
Fixes https://issues.redhat.com/browse/CRT-1449

Modified to comply with openshift naming

---

pkg/test/masteruserrecord/masteruserrecord.go

MUR does not need tier hash labels since NSTemplateSet is handled by Spaces since https://github.com/codeready-toolchain/host-operator/pull/595

Remove Tier Hash Labels From MUR Test Functions

---

.github/workflows/ci-build.yml
.github/workflows/ci-check-gomod-alt.yml
.github/workflows/ci-check-gomod.yml
.github/workflows/ci-check.yml

Use a separate workflow triggered when changes happen on 'go.mod' only

chore: check go.mod replacement when applicable only

---

pkg/socialevent/socialevent_name_generator.go
pkg/socialevent/socialevent_name_generator_test.go

generates unique random names in the `XXXX-XXXX-XXXX-XXXX` format,
using the `abcdefghjklmnpqrstuvwxyz` letters and `23456789` figures,
making it a valid resource name which can also be used as an
activation code.

feat: new SocialEvent name generator

---

pkg/test/usersignup/usersignup.go

This PR modifies the `NewUserSignup()` function to set the resource name the same as the username.
Fixes https://issues.redhat.com/browse/CRT-1503

Set username equal to UserSignup name when creating new UserSignups

---

pkg/hash/encode.go
pkg/hash/encode_test.go
pkg/test/tier/templateRefs.go
pkg/test/usersignup/usersignup.go

make it generic since the logic to hash with md5 is used in multiple places

utility func to hash

---

pkg/notification/notification_builder.go
pkg/notification/notification_builder_test.go

avoid the case where the notification name would start with `-`
which is forbidden (DNS-1123):
> a lowercase RFC 1123 subdomain must consist of lower case alphanumeric
> characters, ‘-’ or ‘.’, and must start and end with an alphanumeric
> character.

fix(notifications): use UUID when CompliantUsername is empty

---

pkg/spacebinding/spacebinding.go
pkg/spacebinding/spacebinding_test.go

Moving some functions from host-operator to toolchain-common. It will be consumed by sandbox-cli as well.

Move new SpaceBinding func to common

---

pkg/states/state_manager.go
pkg/states/state_manager_test.go
pkg/test/usersignup/usersignup.go

distinguish between automatic approval and manual approval (by admin)
see also:
- https://github.com/codeready-toolchain/member-operator/pull/389
- https://github.com/codeready-toolchain/host-operator/pull/702
- https://github.com/codeready-toolchain/registration-service/pull/286
- https://github.com/codeready-toolchain/sandbox-sre/pull/810
- https://github.com/codeready-toolchain/toolchain-e2e/pull/620

refactor: usersignup approved funcs

---

codecov.yaml

`pkg/test/` folder contains files used only for tests - let's drop them from the coverage

exclude test helper files from coverage

---

controllers/toolchaincluster/toolchaincluster_controller_test.go
pkg/test/verify/cluster.go

the current test sets the `tenant` label as part of the setup so it actually doesn't verify that the controller really sets that

fix: don't set tenant label in test setup part

---

codecov.yaml

from https://docs.codecov.com/docs/ignoring-paths
> The pattern folder/* will not match recursively in the folder.
Please use this folder/**/*, which will exclude all files within the given folder.
:man_facepalming:

ignore also subfolders

---

pkg/cluster/cache.go
pkg/cluster/service.go
pkg/cluster/service_test.go
pkg/test/verify/cluster.go

Add Lables filed to CachedToolchainCluster struct so that it can reflect the cluster-role labels enabling filtering on those.
Jira Ticket: https://issues.redhat.com/browse/ASC-251
Related PR's:
- api: https://github.com/codeready-toolchain/api/pull/336
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/736
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/656

feat: Support cluster-roles when specifying the needed target cluster in Spaces

---

pkg/test/config/memberoperatorconfig.go

This will allow us to unit test the WebConsolePlugin config in the same manner that we test other configurations

Added support for WebConsoleConfig in memberoperatorconfig.go

---

go.mod
go.sum
pkg/test/spacebindingrequest/spacebindingrequest_assertions.go

Add test utilities for SpaceBindingRequest controller. 
Those will be used in both host-operator controller unit tests and e2e tests for spacebindingrequests.
Jira: https://issues.redhat.com/browse/ASC-397
Related PRs:
- api https://github.com/codeready-toolchain/api/pull/372
- host https://github.com/codeready-toolchain/host-operator/pull/848
- e2e https://github.com/codeready-toolchain/toolchain-e2e/pull/779

feat: Implement SpaceBindingRequest controller main logic

---

pkg/test/masteruserrecord/masteruserrecord.go

This PR populates the PropagatedClaims property with some hard coded values for testing purposes.

Populate PropagatedClaims when creating a new MasterUserRecord

---

.github/workflows/ci-build.yml
.github/workflows/ci-check-gomod.yml

As of [June 2023][1], GitHub no longer uses node v12 within its actions runner by default.  They have been encouraging action authors to switch to node v16 and [encouraging users][2] to use the new versions of the actions when they become available, with the intent on removing node v12 sometime in the near future.
Bump the versions of the affected actions to bring this in line.
[1]: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[2]: https://github.com/codeready-toolchain/host-operator/actions/runs/6421632076

ci: bump actions to silence node12 warnings

---

pkg/test/masteruserrecord/masteruserrecord.go
pkg/test/masteruserrecord/masteruserrecord_assertion.go
pkg/test/useraccount/useraccount.go
pkg/test/useraccount/useraccount_assertion.go
pkg/test/useraccount/useraccount_test.go

This is a companion PR to https://github.com/codeready-toolchain/host-operator/pull/943 which refactors the MasterUserRecordController to only use the user's SSO claim values from PropagatedClaims and nowhere else.

Update common libraries to use PropagatedClaims

---

go.mod
go.sum
pkg/test/auth/tokenmanager.go
pkg/test/auth/tokenmanager_test.go

Needed for https://github.com/codeready-toolchain/registration-service/pull/391

Update JWT dependency

---

pkg/test/assertions/assertions.go

Marking the AssertThat as a helper method so that error reporting skips it and reports the file position in the actual test.

Marking the AssertThat as a test helper method

---

pkg/test/assertions/assertions.go
pkg/test/assertions/assertions_test.go
pkg/test/assertions/predicates.go
pkg/test/assertions/predicates_test.go
pkg/test/spaceprovisionerconfig/spaceprovisionerconfig_assertions.go
pkg/test/spaceprovisionerconfig/spaceprovisionerconfig_assertions_test.go

This adds additional interface that the Predicate implementations can implement to enable reporting of the differences that caused the predicate to not match. This will be used in the toolchain-e2e wait.For()... methods to aid in debugging the e2e test failures from the logs. The changes in toolchain-e2e are here: https://github.com/codeready-toolchain/toolchain-e2e/pull/897
In toolchain-common, the `AssertThat` function has also been updated to take advantage of this new diffing capability. Before, the output of the `AssertThat` function could be specified similarly to `assert.*` functions using the "message and arguments` array. While this possibility has been removed, the method gained the ability to report the diffs that caused the predicates to fail.
Let's consider the following …

Enable diff reporting on predicates

---

.github/workflows/linters.yml
.github/workflows/test-with-coverage.yml

split the ci-build.yml file into following two files
test-with-coverage.yml
linters.yml
By updating pull_request_target to have tokens the workflow automatically checks out the code from master and not from PR. 
This fix is needed only for the tests to upload codecov report, not for linters and hence spliting the workflow

Split ci-build.yml

---

pkg/cluster/service.go
pkg/template/processor.go
pkg/template/template_test.go

Signed-off-by: Francesco Ilario <filario@redhat.com>

fix some linter's complaints

---

controllers/label_event_handler_test.go
go.mod
go.sum
pkg/template/nstemplatetiers/nstemplatetier_generator.go
pkg/template/nstemplatetiers/nstemplatetier_generator_test.go
pkg/template/nstemplatetiers/testdata/nstemplatetiers/advanced/based_on_tier.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/cluster.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/ns_tenant.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/spacerole_admin.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/spacerole_contributor.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/spacerole_maintainer.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/tier.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/base/cluster.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/base/ns_dev.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/base/ns_stage.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/base/spacerole_admin.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/base/tier.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/nocluster/ns_dev.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/nocluster/ns_stage.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/nocluster/spacerole_admin.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/nocluster/tier.yaml

This PR moves the logic of nstemplatetier_generator.go from host-operator to toolchain-common and make it generic so it can be used by a ksctl command for generating NSTemplateTier & TierTemplate manifests locally in a GitOps repository.
There is almost no change in the logic of the generator, it should work in the same way as it was before, just with the difference that it doesn't load templates from the assets, but takes them from the map passed as a parameter.
[KUBESAW-59](https://issues.redhat.com/browse/KUBESAW-59)
related PR in host-operator repo https://github.com/codeready-toolchain/host-operator/pull/1006

Make NSTemplateTier generator generic

---

.gitleaks.toml
pkg/test/auth/tokenmanager.go

This PR excludes the file `pkg/test/auth/tokenmanager.go` from the GitLeaks checks. It is actually containing a certificate that prevents the git hook to complete successfully.
Signed-off-by: Francesco Ilario <filario@redhat.com>

add .gitleaks.toml

---

controllers/toolchaincluster/healthchecker.go
controllers/toolchaincluster/healthchecker_test.go
controllers/toolchaincluster/toolchaincluster_controller.go
go.mod
go.sum
pkg/cluster/cache_whitebox_test.go
pkg/cluster/service.go
pkg/cluster/service_test.go
pkg/cluster/service_whitebox_test.go
pkg/status/toolchaincluster.go
pkg/status/toolchaincluster_test.go
pkg/test/cluster.go
pkg/test/verify/cluster.go

This is to replace the special ToolchainClusterCondition with the standard toolchain Condition.
This is  Related to Change in 
- API - https://github.com/codeready-toolchain/api/pull/416
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1017
- Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/560
- Toolchain-E2E - https://github.com/codeready-toolchain/toolchain-e2e/pull/955
- KSCTL - https://github.com/kubesaw/ksctl/pull/38
Only change is updating the dependency of API and toolchain-common
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/424
- Sandbox-SRE - https://github.com/codeready-toolchain/sandbox-sre/pull/1706

KUBESAW-43: Replace the special ToolchainClusterCondition with the standard toolchain Condition

---

controllers/toolchaincluster/toolchaincluster_controller.go
controllers/toolchaincluster/toolchaincluster_controller_test.go

`$TITLE`.
With all the clusters already updated, we can remove this migration step. IMHO, we should KEEP the test for the presence of the labels in `toolchain-e2e` (https://github.com/codeready-toolchain/toolchain-e2e/blob/master/test/e2e/toolchaincluster_test.go#L43) until we actually flip the logic and create the `ToolchainCluster`s based on the secrets.

Remove the migration step to add labels to creds secret for ToolchainClusters.

---

pkg/cluster/service.go
pkg/test/cluster.go
pkg/test/verify/cluster.go

[KUBESAW-121](https://issues.redhat.com/browse/KUBESAW-121)
don't read the caBundle and don't set the CAData in the ToolchainCluster client. Instead of it, use the `ToolchainCluster.spec.disabledTLSValidations` to decide if it should use insecure connection or not
see https://github.com/codeready-toolchain/toolchain-cicd/pull/110

fix: don't use CAData in the ToolchainCluster client

---

controllers/toolchaincluster/toolchaincluster_controller.go
controllers/toolchaincluster/toolchaincluster_controller_test.go

This introduces a temporary migration step that converts the connection details spread across the ToolchainCluster and its associated secret into the "kubeconfig" field in the secret data that contains the serialized kubeconfig file with the details all included.
Associated PRs:
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/997
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1042

Store kubeconfig in ToolchainCluster secret

---

make/go.mk

This is to create makefile target for dependency validations in each repository so that this can be used to verify if there are any compilation issues after updating the dependencies of toolchain-common/api
Similar PRs
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1052
- Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/581
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/440
- Toolchain-E2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1002
- KSTCL - https://github.com/kubesaw/ksctl/pull/43

KUBESAW-124: Makefile target for dependency validations

---

controllers/toolchaincluster/healthchecker.go
controllers/toolchaincluster/healthchecker_test.go
controllers/toolchaincluster/toolchaincluster_controller.go
controllers/toolchaincluster/toolchaincluster_controller_test.go

This PR is to refactor the ToolchainCluster controller .
this is related to this [discussion](https://github.com/codeready-toolchain/toolchain-common/pull/386#discussion_r1571030991) and [this ](https://redhat-internal.slack.com/archives/C06MJ2DVBU4/p1713430967057339?thread_ts=1713362133.858979&cid=C06MJ2DVBU4) . 
Related PR where only change is updating the dependency But paired E2e has changes as Offline condition is dropped
- Host-operator - https://github.com/codeready-toolchain/host-operator/pull/1049
- Paired e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1005
- Member-operator - https://github.com/codeready-toolchain/member-operator/pull/579
- Paired e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1006
- Registration-Service - …

KUBESAW-100: Refactoring toolchaincluster controller

---

go.mod
go.sum
pkg/banneduser/banneduser.go
pkg/banneduser/banneduser_test.go

- add NewBannedUser and IsAlreadyBanned funcs to avoid duplicate this work across the repos
[SANDBOX-674](https://issues.redhat.com/browse/SANDBOX-674)
Associated PRs:
- api: https://github.com/codeready-toolchain/api/pull/436
- workload-analyzer: https://github.com/codeready-toolchain/workload-analyzer/pull/12

SANDBOX-674: add NewBannedUser and IsAlreadyBanned funcs

---

controllers/toolchaincluster/toolchaincluster_controller.go
controllers/toolchaincluster/toolchaincluster_controller_test.go
pkg/banneduser/banneduser.go
pkg/banneduser/banneduser_test.go

- improve IsAlreadyBanned func to return the BannedUser when the user was already banned. It will be useful for ksctl
- fix some assertions and clean imports being imported more than once
[SANDBOX-674](https://issues.redhat.com/browse/SANDBOX-674)
Associated PRs:
- workload-analyzer: https://github.com/codeready-toolchain/workload-analyzer/pull/12

improve IsAlreadyBanned

---

.github/workflows/linters.yml
.github/workflows/test-with-coverage.yml

uses go-version-file instead of go-version. One less place to change when making updates.
Changes order in github action to first checkout code and then install go.
related PRs:
https://github.com/codeready-toolchain/api/pull/434

SANDBOX-677 use go-version-file

---

controllers/toolchainclustercache/namespace_predicate.go
controllers/toolchainclustercache/namespace_predicate_test.go
controllers/toolchainclustercache/toolchaincluster_cache_controller.go

https://redhat-internal.slack.com/archives/C06MJ2DVBU4/p1721927428487549?thread_ts=1721925588.145229&cid=C06MJ2DVBU4
Related PR 
Host Operator - https://github.com/codeready-toolchain/host-operator/pull/1067
Member Operator - https://github.com/codeready-toolchain/member-operator/pull/587

cache ToolchainCluster CR only in the given namespace

---

go.mod
go.sum
pkg/configuration/memberoperatorconfig/configuration.go
pkg/configuration/memberoperatorconfig/configuration_test.go
pkg/test/config/memberoperatorconfig.go

Pendo has been decommisioned, we don't need this plugin anymore

remove webConsolePlugin from ToolchainClusterConfig (phase 2)

---

pkg/test/metrics/metric.go

move to toolchain-common to avoid cyclic import dependencies.

move wrapper for metric float comparision to common

---

pkg/notification/notification_builder.go
pkg/notification/notification_builder_test.go
pkg/test/tier/usertier.go

So we can use the deactivation timeout days in the user-provisioned email templates from the corresponding user tier.
Part of https://issues.redhat.com/browse/SANDBOX-741

Add User Tier context to Notification Builder

---

controllers/toolchaincluster/healthchecker_test.go
controllers/toolchaincluster/toolchaincluster_controller.go
controllers/toolchaincluster/toolchaincluster_controller_test.go
pkg/cluster/service.go
pkg/cluster/service_test.go
pkg/cluster/service_whitebox_test.go
pkg/test/cluster.go
pkg/test/verify/cluster.go

Remove the migration step to kubeconfig and update the tests to not test for the legacy fields in ToolchainCluster.
This a follow-up of https://github.com/codeready-toolchain/toolchain-common/pull/412 that updates the testsuite to not rely on the legacy fields that defined the connection settings for the clusters.
This is safe to do, because all of our clusters have already been upgraded and have the kubeconfigs generated in the connection secrets.
Related PRs:
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/412
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1058
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/1012

Remove the migration step to kubeconfig

---

pkg/test/cluster.go

This PR prepares `toolchain-common` for removal of most fields from the `ToolchainCluster` spec. The only field that will eventually remain is the secret reference. All the rest of the fields have either been moved to the status of the `ToolchainCluster` already or are part of the kubeconfig that is stored in the referenced secret.
NOTE: that this PR does NOT update the dependency to the API. That is to avoid breakage during the relatively long time it will take to update all the components with the necessary changes. Once we merge this PR, I will create a number of additional PRs in the rest of the components that will use the new version of `toolchain-common` and make necessary updates in the components to not use the outdated fields of `ToolchainCluster`. Only once those PRs are …

Don't use fields of ToolchainCluster spec

---

scripts/verify-replace.sh

Introduce a make command for pre-requisite of verify-replace script as host-operator and member operator require tiers and assets to be ready before any changes to go mod
Related PRs:
Host Operator - https://github.com/codeready-toolchain/host-operator/pull/1091
Member Operator - https://github.com/codeready-toolchain/member-operator/pull/599 
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1049 
Registration service - https://github.com/codeready-toolchain/registration-service/pull/465
Ksctl - https://github.com/kubesaw/ksctl/pull/81

KUBESAW-192: Introduce a make command for pre-requisite of verify-replace script

---

make/clean.mk
make/go.mk

Fix the make help command which was not showing the targets without comments, also remove the `vendor` support as not needed anymore.

fix make help and cleanup vendor references

---

go.mod
go.sum
pkg/test/spaceprovisionerconfig/spaceprovisionerconfig.go
pkg/test/spaceprovisionerconfig/spaceprovisionerconfig_assertions.go
pkg/test/spaceprovisionerconfig/spaceprovisionerconfig_assertions_test.go

This just adds a couple of utility functions and predicates to be used by the tests on the new `SpaceProvisionerConfig.Status.ConsumedCapacity`. The functions will be used in code in the host operator and e2e tests in the upcoming PRs.

Add utility functions to support tests on SpaceProvisionerConfig.Status.ConsumedCapacity

---

controllers/toolchainclustercache/toolchaincluster_cache_controller.go

Use LabelsAndGenerationPredicate for ToolchainClusterCache controller to prevent it from reconciling unnecessarily. It's especially relevant since the health checker was included in the ToolchainCluster controller: https://github.com/codeready-toolchain/member-operator/blob/50180a07ca25f97123bf4cc614e801b542beb6cb/main.go#L231 which triggers ToolchainConfig status updates every 10 seconds.

Use LabelsAndGenerationPredicate for ToolchainClusterCache controller

---

make/go.mk

Introduce a make command for pre-requisite of verify-replace script
Initially this was not required to be run from the api repo, but now this same error started appearing while running from api repo too hence adding the make command to be similar to [PR](https://github.com/codeready-toolchain/host-operator/pull/1091)

Introduce a make command for pre-requisite of verify-replace

---

.github/workflows/linters.yml
pkg/status/componentconditions.go

Updating the GolangciLint to v1.63.1 across all repos and fixing the [linter error](https://github.com/codeready-toolchain/toolchain-common/actions/runs/12649409591/job/35245760745?pr=442#step:4:29) which were caught as a result of upgrading the linter
Similar PRs
- API - https://github.com/codeready-toolchain/api/pull/454
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1116
- Member-Operator - Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/612
- Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/491
- Toolchain E2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1092
- Ksctl - https://github.com/kubesaw/ksctl/pull/97

KUBESAW-250: Updating GolangCiLint to v1.63.1

---

pkg/test/usersignup/usersignup.go

https://github.com/codeready-toolchain/registration-service/pull/492#discussion_r1908857922
TODO: 
- EDIT: the only repo that needed additional changes was host-operator - related PR https://github.com/codeready-toolchain/host-operator/pull/1121

align UserSignup hepler functions

---

scripts/verify-replace.sh

This PR is to update the verify dependency script such a way that it prints the error/failure in an understandable way
Similar PR
- API - https://github.com/codeready-toolchain/api/pull/458

KUBESAW-174: Print error output for repos where verification failed

---

pkg/cluster/service.go

- clean unnecessary copy. With go 1.22, we do not need it. For more info, check https://go.dev/blog/loopvar-preview
Related PRs:
- https://github.com/codeready-toolchain/toolchain-e2e/pull/1133
- https://github.com/codeready-toolchain/host-operator/pull/1157
- https://github.com/codeready-toolchain/member-operator/pull/641
- https://github.com/kubesaw/ksctl/pull/108
- wa pr 149

clean unnecessary copy

---

pkg/utils/stringhelper.go
pkg/utils/stringhelper_test.go

Move string helper utility to common so that it can be used in other repos for splitting the features annotation into a slice.
Jira: https://issues.redhat.com/browse/KUBESAW-142
Related to:
https://github.com/codeready-toolchain/member-operator/pull/648
https://github.com/codeready-toolchain/toolchain-e2e/pull/1137

feat: add string helper

---

.github/workflows/linters.yml
.golangci.bck.yml
.golangci.yml
pkg/banneduser/banneduser_test.go
pkg/client/client.go
pkg/client/rest_client_test.go
pkg/configuration/load_test.go
pkg/configuration/memberoperatorconfig/configuration_test.go
pkg/notification/notification_builder.go
pkg/proxy/workspace.go
pkg/status/versionchecks.go
pkg/template/nstemplatetiers/nstemplatetier_generator_test.go
pkg/test/client_test.go
pkg/test/condition.go
pkg/test/nstemplateset/nstemplateset.go
pkg/test/nstemplateset/nstemplateset_assertion.go
pkg/test/space/space.go
pkg/test/spacebindingrequest/spacebindingrequest.go
pkg/test/status.go
pkg/test/usersignup/usersignup.go

upgraded `.golangci.yml` with `golangci-lint migrate`
include fixes suggested by `golangci-lint run -c ./.golangci.yml`

chore(build): migrate to golangci-lint@v2 and golangci-lint-action@v7

---

.github/workflows/verify-dependencies.yml

update the golangci-lint version in the verify-dependencies GH action to be in line with the version in linters.yaml

update the golangci-lint version in the verify-dependencies GH action

---

pkg/client/ssa_client.go
pkg/client/ssa_client_test.go

The migration from CSA (client-side-apply) to SSA is in the end needed (we first thought we could do without it), because the "dangling" update entries in the managed fields could prevent the automatic field removal in some future update (that could happen many operator versions later, as long as the object still survives from the times where our operators didn't use SSA for creating/updating objects in the cluster).

Add migration support to the SSA client

---

pkg/template/nstemplatetiers/nstemplatetier_generator.go
pkg/template/nstemplatetiers/nstemplatetier_generator_test.go
pkg/template/nstemplatetiers/testdata/nstemplatetiers/appstudio/cluster.yaml
pkg/template/nstemplatetiers/testdata/nstemplatetiers/base/cluster.yaml

Simplify nstemplatetiers.GenerateTiers to not distiniguish between create/update in the EnsureObject func. This is in preparation for using the SSA client that doesn't do that either.
Related PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1185
- ksctl: https://github.com/kubesaw/ksctl/pull/119
- toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/1169
JIRA: https://issues.redhat.com/browse/SANDBOX-1339

Simplify nstemplatetiers.GenerateTiers
